### ISSUE TITLE
Json output for completion rate

### ISSUE THREAD

**Issue by tomwm** [ministryofjustice/atet#725]
In order to fulfil the completion rate on the performance platform https://www.gov.uk/performance/make-a-claim-to-an-employment-tribunal

Create json output for the following:
- completed claims over 91 days
- claims in a saved state over 91 days

**Comment by tomwm** [comment]
@TrentDSD is that description accurate?

**Comment by TrentDSD** [comment]
Yeah that matches Urmy's description of:
- number completes (both start and complete timestamps) in the previous 91 days
- number started (start timestamp but no complete timestamp) in the previous 91 days

There's a question as to whether 'started' means 'saved'. Arguably we should only consider claims that are eligible for completion over that period. So that would only include those where at least some information has been submitted.

**Comment by tomwm** [comment]
Right, 'started' should actually mean they have hit 'claimant details' page.



On 29 April 2015 at 16:57, Trent Greenwood <notifications@github.com> wrote:

> Yeah that matches Urmy's description of:
>
>    - number completes (both start and complete timestamps) in the
>    previous 91 days
>    - number started (start timestamp but no complete timestamp) in the
>    previous 91 days
>
> There's a question as to whether 'started' means 'saved'. Arguably we
> should only consider claims that are eligible for completion over that
> period. So that would only include those where at least some information
> has been submitted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ministryofjustice/atet/issues/725#issuecomment-97479523>
> .
>



-- 
Tom Wynne-Morgan
Product Manager
*Ministry of Justice Digital Services*

*https://www.google.com/calendar/embed?src=tom.wynne-morgan%40digital.justice.gov.uk&ctz=Europe/London
<https://www.google.com/calendar/embed?src=tom.wynne-morgan%40digital.justice.gov.uk&ctz=Europe/London>
*

tom.wynne-morgan@digital.justice.gov.uk <tom.dolan@digital.justice.gov.uk>
